// Code generated by "stringer -type=Op -trimprefix=Op gx"; DO NOT EDIT.

package gx

import "strconv"

const _Op_name = "JMPJMPTJMPFLABELEMITSTORELOADLOADGDEREFMUTCONSTEQNEQLTLTEGTGTECALLADDSUBMULDIV"

var _Op_index = [...]uint8{0, 3, 7, 11, 16, 20, 25, 29, 34, 39, 42, 47, 49, 52, 54, 57, 59, 62, 66, 69, 72, 75, 78}

func (i Op) String() string {
	if i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
