// Code generated by "stringer -type=Op -trimprefix=Op vm"; DO NOT EDIT.

package vm

import "strconv"

const _Op_name = "CONDLABELEMITSTORELOADLOADGDEREFMUTCONSTDUPEQNEQLTLTEGTGTECALLADDSUBMULDIV"

var _Op_index = [...]uint8{0, 4, 9, 13, 18, 22, 27, 32, 35, 40, 43, 45, 48, 50, 53, 55, 58, 62, 65, 68, 71, 74}

func (i Op) String() string {
	if i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
