// Code generated by "stringer -type=Op -trimprefix=Op vm"; DO NOT EDIT.

package vm

import "strconv"

const _Op_name = "CONDLABELEMITSTORELOADLOADGDEREFCONSTANDOREQNEQLTLTEGTGTECALLADDSUBMULDIV"

var _Op_index = [...]uint8{0, 4, 9, 13, 18, 22, 27, 32, 37, 40, 42, 44, 47, 49, 52, 54, 57, 61, 64, 67, 70, 73}

func (i Op) String() string {
	if i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
